// FABgen output .h
// This file is automatically generated, do not modify manually!

#pragma once

#include <cstdint>

#include <cstddef>

/*
	pass the get_c_type_info function from another binding to this function to resolve external types declared in this binding.
	you will need to write a wrapper to cast the type_info * pointer to the correct type if you are using a binding prefix.
	this function returns the number of unresolved external symbols.
*/
size_t gen_link_binding(gen_type_info *(*get_c_type_info)(const char *));

