// FABgen output .fs 
// This file is automatically generated, do not modify manually!
open System.Runtime.InteropServices
open System
#if WINDOWS
[<DllImport("VectorsSharedLibraries.dll")>]
#else
[<DllImport("VectorsSharedLibraries.dylib")>]
#endif
 